= hier(7)

== Name

hier - overview of the filesystem layout

== Description

On Mutiny, a filesystem layout is used that attempts to both preserve relative compatibility with
the *Filesystem Hierarchy Standard*, while also making it a priority to reduce cruft, legacy, and
other unnecessary redundancy where possible.

=== Hierarchy

:pp: ++

:fn-devtmpfs: footnote:[devtmpfs does not currently have a manual page, and documentation of it \
                        in the kernel is slim. See CONFIG_DEVTMPFS and CONFIG_DEVTMPFS_MOUNT in \
                        the kernel configuration to see descriptions of what it does.]

The following is a sketch of the filesystem hierarchy.

_/_::
    The root of the filesystem. From here, all flows forth. This is additionally the root user's
    home directory.

    _/boot_:::
        Files used during the boot process, such as boot loader configuration, kernel executables,
        initramfs archives, and so on. If running on an EFI-enabled system, this whole directory
        should be mounted on an EFI partition.

    _/bin_:::
        Binaries installed on the system by the package manager, <<praxis.7.adoc#,praxis(7)>>, or
        through some other system-managed method.

    _/dev_:::
        Device files. This structure is first populated by devtmpfs{fn-devtmpfs} at boot, and then
        after boot, managed by mdevd(8).

    _/etc_:::
        System configuration. This directory is first populated by tendency-config-populate(1).

        _ksh/_::::   Files relating to ksh(1).

            * _rc_ - Startup file for ksh(1), sourced by _/etc/profile_. See profile(7).

        _fstab_::::     **F**ile**s**ystem **t**able. It is for specifying what filesystems can be
                        mounted, and it's used by commune-init(8) and mount(8) to mount your
                        filesystems at boot. See fstab(5).

        _group_::::     A list of groups on the system. See group(5).

        _hosts_::::     A table of IP addresses associated with hostnames. See hosts(5).

        _issue_::::     A file containing the message shown prior to the login prompt, printed by
                        getty(8).

        _passwd_::::    A list of user accounts on the system. This should be readable by all
                        users. See passwd(5).

        _profile_::::   A sh(1) script ran for login shells. See profile(7).

        _shadow_::::    A "shadowed" passwd file: that is to say, it contains encrypted passwords,
                        while */etc/passwd* does not. Fittingly, it should not be readable by
                        anyone except root. See shadow(5).

        _shells_::::    A list of the shells a user can have as their login shell. See shells(5).

    _/home_:::
        Non-system users' home directories. There's no specified directory structure within this
        directory, but usually all non-system users will have a directory under this one as their
        home directory.

    _/include_:::
        Header files for C and C++ libraries installed by the package manager,
        <<praxis.7.adoc#,praxis(7)>>, or through some other system-managed method, used by their
        respective compilers, cc(1) and c{pp}(1).

    _/lib_:::
        Libraries and other non-user-facing executables installed by the package manager, praxis(7),
        or through some other system-managed method.

        _os-release_::::    File containing metadata about the installed OS.

    _/local_:::
        System administrator-managed prefix. Everything under /local is effectively free reign for
        the user to add things without them being touched by any system management things;
        <<praxis.7.adoc#,praxis(7)>> never install anything within here.

    _/mnt_:::
        Mounted filesystems. They may or may not be filesystems mounted from hotpluggable devices.
        There's no specified directory structure within here.

    _/proc_:::
        The mountpoint of a pseudo-filesystem that provides a filesystem interface to _some_ data in
        the kernel. Most notably, it contains a folder for each process ID on the system.
        See proc(5) for more details.

    _/run_:::
        Runtime files. That is, files that pertain to the system since it booted up, in some way;
        they hold no permanance and are never backed by an actual persistent storage.
        It is mounted as a tmpfs(5) filesystem, and exists only in RAM.

        _tmp_::::           Various temporary files. This is also mounted as a secondary tmpfs(5).
                            The contents of this directory is visible to all users of the system.

        _user_::::          User-specific runtime files.

            _<UID>_:::::    Runtime files which are controlled by the user ID _UID_.
                            Each directory is created when the user logs in--see login(7).
                            This directory is marked read/write/execute only for the owner.

// TODO(somasis): Document the following:
// │           └── commune     - User's supervision trees, maintained by `commune` scopes.
// │               ├── snooze  - Corresponds to the running supervision tree for user's jobs.
// │               │             Maintained by `commune-snooze`.
// │               ├── user    - Corresponds to the running supervision tree for the user.
// │               │             Maintained by `commune-user`.
// │               └── xinit   - Corresponds to the running supervision tree for the user's Xorg
// │                             session. Maintained by `commune-xinit`.

    _/share_:::
        Resources of various types, installed on the system by the package manager,
        <<praxis.7.adoc#,praxis(7)>>, or through some other system-managed method.

        _man_::::           System man(1) pages.
                            `man*` directories under this correspond to manual sections.

    _/srv_:::
        Data served by the system. Most commonly, data served by daemons running on the system,
        like an HTTP daemon, git-daemon(1), and so on.

    _/sys_:::
        The mountpoint of a pseudo-filesystem that provides a filesystem interface to kernel data
        structures. See sysfs(5).

    _/var_:::
        Persistent, mutable system data. Data that system programs might need sooner or later, and
        that might change over multiple boots of the system. Things like databases, logs, caches.

        _cache_::::         Cache files.

        _lib_::::           Databases and state files.

        _log_::::           Log files.

        _tmp_::::           Persistent, yet temporary files. It persists across boots, in contrast
                            to _/run/tmp_.

// TODO(somasis): Document the following:
// var                     - Persistent system data.
// ├── cache               - Cache for system programs.
// │   └── praxis
// │       └── distfiles   - Downloaded source for packages.

=== Symbolic links

A few symbolic links are used in the file hierarchy so as to facilitate compatibilty with some
usually-common locations that Mutiny does not use.

_/sbin_::
    A symbolic link to "_bin_". Mutiny merges a lot of (nowadays) redundant directories.
    This one is from the era of Unix when _/bin_ and _/sbin_ were kept separate.

_/tmp_::
    A symbolic link to "_run/tmp_", so as not to disturb applications that expect this to be the
    temporary filesystem.

_/usr_::
    A symbolic link to "_._" (dot). Mutiny merges a lot of (nowadays) redundant directories.
    This one is from the era of Unix when _/usr/bin_ and _/bin_ were kept separate.

_/var/run_::
    A symbolic link to "_../run_". This is a location that has been used in the past for runtime
    data, in version 2.3 of the Filesystem Hierarchy Standard. In version 3.0, it was deprecated in
    favor of _/run_, but suggests a symbolic link be made.

== See also

:fhsv23: https://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html
:fhsv30: https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html
:usrsplit: http://lists.busybox.net/pipermail/busybox/2010-December/074114.html

https://www.freedesktop.org/software/systemd/man/file-hierarchy.html[file-hierarchy(7)]

Filesystem Hierarchy Standard Group, {fhsv23}[_The Filesystem Hierarchy Standard, version 2.3_],
January 29, 2004.

LSB Workgroup, The Linux Foundation, {fhsv30}[_The Filesystem Hierarchy Standard, version 3.0_],
June 3, 2015.

Rob Landley, {usrsplit}[_Understanding the bin, sbin, usr/bin, usr/sbin Split_], December 9, 2010.

include::footer.adoc[]
