= profile(7)

== Name

profile - files used for the startup of login/interactive shells

== Description

When a shell is started, a few files get read. The order used on Mutiny systems is documented here,
and the default actions of the profile files given is explained here.

=== Order

If the shell is a login shell, the following files are read:

1. _/etc/profile_

2. _/share/profile.d/*.sh_ - system-maintained profile files installed by the package manager,
   praxis(7).

3. A shell-specific, admin-managed profile:

    * On ksh(1), this is _/etc/ksh/profile_.
    * On sh(1), this is _/etc/sh/profile_.

4. _~/.profile_. If a shell is not a login shell, no further files are read.

If the shell is an interactive shell, the following files are read:

1. A shell-specific, admin-managed rc file:


2. A user-maintained, shell-specific rc file:

    * On ksh(1), this is either _~/.kshrc_ or _~/.config/ksh/rc_. _~/.kshrc_ takes priority.
    * On sh(1), this is either _~/.shrc_ or _~/.config/sh/rc_. _~/.shrc_ takes priority.

On both ksh(1) and sh(1), the file that will be used is specified via the $ENV environment variable.
See their respective manuals for details on that.

Lastly, if it is an interactive login shell, both sets are read in the order they are listed.

=== Purpose

TODO(somasis): describe what all the disparate files actually do

== Glossary

interactive shell::
    A shell that is started for the purpose of running commands. That is, it prints a prompt, the
    user is expected to be typing commands into it and so on. This corresponds to the *-i* flag.

login shell::
    A shell started with the *-l* flag, or with its argv[0] starting with a dash.
    Less obtusely, this means a shell started by a variety of methods:

        * By a user logging in via login(1), from a virtual terminal
        * By a user logging in via ssh(1), interactively
        * Some terminals can spawn login shells if you tell them to.

== Bugs

There's an IRC channel at irc://irc.freenode.net/#mutiny. Please don't hesitate to message if you
have questions, bug reports, etc.

== See also

ksh(1), sh(1), xdg(7)

== License

*Mutiny* is in the public domain.

To the extent possible under law, Kylie McClain has waived all copyright and related or neighboring
rights to this work.

http://creativecommons.org/publicdomain/zero/1.0/
